export const WS_EVENT_AUTHENTICATION = 'WS_EVENT_AUTHENTICATION';
export const WS_EVENT_SUBSCRIPTION = 'WS_EVENT_SUBSCRIPTION';

export const WS_NEW_SUBSCRIPTION_EVENT = 'WS_NEW_SUBSCRIPTION_EVENT';

// Subscribe
export enum WS_SUBSCRIBE_EVENTS {
  TO_LATEST_WALL = 'WS_EVENT_SUBSCRIBE_TO_LATEST_WALL',
  TO_HASHTAG_WALL = 'WS_EVENT_SUBSCRIBE_TO_HASHTAG_WALL',
  TO_CHARACTER_WALL = 'WS_EVENT_SUBSCRIBE_TO_CHARACTER_WALL',
  TO_CORPORATION_WALL = 'WS_EVENT_SUBSCRIBE_TO_CORPORATION_WALL',
  TO_ALLIANCE_WALL = 'WS_EVENT_SUBSCRIBE_TO_ALLIANCE_WALL',
  TO_POST_COMMENTS = 'WS_EVENT_SUBSCRIBE_TO_POST_COMMENTS',
}

// UnSubscribe
export enum WS_UN_SUBSCRIBE_EVENTS {
  FROM_LATEST_WALL = 'WS_EVENT_UN_SUBSCRIBE_FROM_LATEST_WALL',
  FROM_HASHTAG_WALL = 'WS_EVENT_UN_SUBSCRIBE_FROM_HASHTAG_WALL',
  FROM_CHARACTER_WALL = 'WS_EVENT_UN_SUBSCRIBE_FROM_CHARACTER_WALL',
  FROM_CORPORATION_WALL = 'WS_EVENT_UN_SUBSCRIBE_FROM_CORPORATION_WALL',
  FROM_ALLIANCE_WALL = 'WS_EVENT_UN_SUBSCRIBE_FROM_ALLIANCE_WALL',
  FROM_POST_COMMENTS = 'WS_EVENT_UN_SUBSCRIBE_FROM_POST_COMMENTS',
}

export enum WS_SUBSCRIPTIONS {
  TO_LATEST_WALL = 'WS_EVENT_SUBSCRPTION_TO_LATEST_WALL',
  TO_HASHTAG_WALL = 'WS_EVENT_SUBSCRPTION_TO_HASHTAG_WALL',
  TO_CHARACTER_WALL = 'WS_EVENT_SUBSCRPTION_TO_CHARACTER_WALL',
  TO_CORPORATION_WALL = 'WS_EVENT_SUBSCRPTION_TO_CORPORATION_WALL',
  TO_ALLIANCE_WALL = 'WS_EVENT_SUBSCRPTION_TO_ALLIANCE_WALL',
  TO_POST_COMMENTS = 'WS_EVENT_SUBSCRPTION_TO_POST_COMMENTS',
}
