export enum NOTIFICATION_TYPE {
  NEW_POST_ON_YOUR_WALL = 'NEW_POST_ON_YOUR_WALL',
  NEW_POST_ON_YOUR_CORPORATION_WALL = 'NEW_POST_ON_YOUR_CORPORATION_WALL',
  NEW_POST_ON_YOUR_ALLIANCE_WALL = 'NEW_POST_ON_YOUR_ALLIANCE_WALL',
  NEW_COMMENT_ON_YOUR_POST = 'NEW_COMMENT_ON_YOUR_POST',
  NEW_COMMENT_ON_A_POST_YOU_PARTICIPATE = 'NEW_COMMENT_ON_A_POST_YOU_PARTICIPATE',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
}

export const WS_NOTIFICATION_EVENT = 'WS_NOTIFICATION_EVENT';
export const WS_NOTIFICATION_SEEN_EVENT = 'WS_NOTIFICATION_SEEN_EVENT';
