export const GOOGLE_PUB_SUB_PROVIDER = 'GOOGLE_PUB_SUB_PROVIDER';
export const GOOGLE_PUB_SUB_CONFIG = 'GOOGLE_PUB_SUB_CONFIG';

export const GOOGLE_PUB_SUB_TOPIC = 'GOOGLE_PUB_SUB_TOPIC';
export const GOOGLE_PUB_SUB_SUBSCRIPTION = 'GOOGLE_PUB_SUB_SUBSCRIPTION';

export const GOOGLE_PUB_SUB_PUBLISHER_OPTIONS = 'GOOGLE_PUB_SUB_PUBLISHER_OPTIONS';
export const GOOGLE_PUB_SUB_SUBSCRIBER_OPTIONS = 'GOOGLE_PUB_SUB_SUBSCRIBER_OPTIONS';

export const GOOGLE_PUB_SUB_CONFIG_USE_ENV = Symbol('GOOGLE_PUB_SUB_CONFIG_USE_ENV');
