export enum WS_REDIS_EVENTS {
  LATEST_WALL = 'WS_REDIS_EVENT_LATEST_WALL',
  HASHTAG_WALL = 'WS_REDIS_EVENT_HASHTAG_WALL',
  CHARACTER_WALL = 'WS_REDIS_EVENT_CHARACTER_WALL',
  CORPORATION_WALL = 'WS_REDIS_EVENT_CORPORATION_WALL',
  ALLIANCE_WALL = 'WS_REDIS_EVENT_ALLIANCE_WALL',

  POST_COMMENTS = 'WS_REDIS_EVENT_POST_COMMENTS',

  CHARACTER = 'WS_REDIS_EVENT_CHARACTER',
}
